spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: ca.concordia.pojo
